/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms. */
#include <stdio.h>

int fibonacciSequence(int max_val);
int isEven(int num);

int main()
{
    fibonacciSequence(4000000);
}

int fibonacciSequence(int max_val)
{
    int i = 1;
    int sum = 3;
    int sumEven = 0;
    int j;
    for(j = 2; j < max_val; sum = i + j)
    {
        i = j;
        j = sum;
       

        if(isEven(i) == 1)
        {
            sumEven = sumEven + i;
            
        }
    }
    printf("Sum of even numbers = %d\n", sumEven);
    return 0;
}

int isEven(int num)
{
    int remainder = num % 2;

    if(remainder == 0)
    {
        return 1;
    }
    else
    {
        return 0;
    }
}